import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { useRouter } from "expo-router";

import { nest, ApiError, type AdminPayout } from "@/src/api/nest";
import { Button } from "@/src/components/Button";
import { EmptyState } from "@/src/components/EmptyState";
import { toast } from "@/src/components/Toast";
import { useAuth } from "@/src/context/AuthContext";
import { colors, radius, shadows, spacing } from "@/src/theme";
import { haptics } from "@/src/utils/haptics";
import { safeBack } from "@/src/utils/nav";

const money=(n:number,c:string)=>`${c||"USD"} ${Number(n||0).toFixed(2)}`;
export default function PayoutAdmin(){
  const router=useRouter();const insets=useSafeAreaInsets();const{user}=useAuth();
  const[items,setItems]=useState<AdminPayout[]>([]);const[refs,setRefs]=useState<Record<number,string>>({});const[working,setWorking]=useState<number|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{if(user?.role!=="admin")return;try{const r=await nest.adminListPayouts({status:"all",per_page:50});setItems((r.items||[]).filter(p=>!["paid","cancelled"].includes(p.status)));}catch(e){toast.error(e instanceof ApiError?e.friendly:"Could not load payouts");}finally{setLoading(false);setRefreshing(false);}},[user?.role]);React.useEffect(()=>{void load();},[load]);
  const process=async(p:AdminPayout)=>{if(p.method==="manual"&&!String(refs[p.id]||p.external_id||"").trim())return toast.error("Enter the ACH / bank confirmation reference first");setWorking(p.id);try{await nest.adminProcessPayout(p.id,{external_id:String(refs[p.id]||p.external_id||"").trim(),notes:"Processed from MyNest mobile operations."});toast.success(p.method==="manual"?"Payout marked paid":"Payout submitted");await load();}catch(e){toast.error(e instanceof ApiError?e.friendly:"Could not process payout");}finally{setWorking(null);}};
  const retry=async(p:AdminPayout)=>{setWorking(p.id);try{await nest.adminRetryPayout(p.id);toast.success("Payout returned to processing queue");await load();}catch(e){toast.error(e instanceof ApiError?e.friendly:"Could not retry payout");}finally{setWorking(null);}};
  const cancel=(p:AdminPayout)=>Alert.alert("Cancel payout?","The reserved balance will be returned to the seller's available balance.",[{text:"Keep",style:"cancel"},{text:"Cancel payout",style:"destructive",onPress:async()=>{setWorking(p.id);try{await nest.adminCancelPayout(p.id,"Cancelled from MyNest mobile operations.");setItems(x=>x.filter(i=>i.id!==p.id));toast.success("Payout cancelled");}catch(e){toast.error(e instanceof ApiError?e.friendly:"Could not cancel payout");}finally{setWorking(null);}}}]);
  if(user?.role!=="admin")return <SafeAreaView style={styles.safe} edges={["top"]}><Top onBack={()=>safeBack(router, "/admin/operations")}/><EmptyState icon="lock-closed-outline" title="Not available" message="Admin access is required."/></SafeAreaView>;
  if(loading)return <SafeAreaView style={styles.safe} edges={["top"]}><Top onBack={()=>safeBack(router, "/admin/operations")}/><View style={styles.center}><ActivityIndicator color={colors.brand}/></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe} edges={["top"]}><Top onBack={()=>safeBack(router, "/admin/operations")}/><ScrollView contentContainerStyle={{padding:spacing.lg,paddingBottom:insets.bottom+40}} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}} tintColor={colors.brand}/>} keyboardShouldPersistTaps="handled">
    {!items.length?<EmptyState icon="checkmark-circle-outline" title="Queue clear" message="No payouts require action."/>:items.map(p=><View key={p.id} style={styles.card}><View style={styles.row}><View style={{flex:1}}><Text style={styles.title}>{p.seller_name||`Seller #${p.seller_id}`}</Text><Text style={[styles.status,["failed","returned"].includes(p.status)&&{color:colors.error}]}>{p.status.replace(/_/g," ")} · {p.method}</Text></View><Text style={styles.amount}>{money(p.amount,p.currency)}</Text></View><Text style={styles.meta}>{p.destination||p.seller_email}</Text>{p.method==="manual"&&["requested","processing"].includes(p.status)?<TextInput value={refs[p.id]??p.external_id??""} onChangeText={v=>setRefs(r=>({...r,[p.id]:v}))} autoCapitalize="characters" placeholder="ACH / bank confirmation reference" placeholderTextColor={colors.onSurfaceMuted} style={styles.input}/>:null}{p.method==="paypal"&&p.status==="processing"&&p.external_id?<View style={styles.providerWait}><Ionicons name="time-outline" size={16} color={colors.brand}/><Text style={styles.providerWaitText}>Submitted to PayPal · awaiting provider confirmation</Text></View>:["requested","processing"].includes(p.status)?<Button title={p.method==="manual"?"Mark paid":"Process payout"} size="sm" onPress={()=>void process(p)} loading={working===p.id} style={{marginTop:spacing.md}}/>:<Button title="Retry payout" size="sm" onPress={()=>void retry(p)} loading={working===p.id} style={{marginTop:spacing.md}}/>}{!(p.method==="paypal"&&p.status==="processing"&&p.external_id)?<Button title="Cancel payout" size="sm" variant="ghost" onPress={()=>cancel(p)} disabled={working===p.id} style={{marginTop:spacing.xs}}/>:null}</View>)}
  </ScrollView></SafeAreaView>;
}
function Top({onBack}:{onBack:()=>void}){return <View style={styles.top}><TouchableOpacity onPress={()=>{haptics.tap();onBack();}} style={styles.topBtn} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }} accessibilityRole="button" accessibilityLabel="Go back"><Ionicons name="chevron-back" size={22} color={colors.onSurface}/></TouchableOpacity><Text style={styles.topTitle}>Payouts</Text><View style={{width:40}}/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.surface},center:{flex:1,alignItems:"center",justifyContent:"center"},top:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",padding:spacing.md},topBtn:{width:40,height:40,alignItems:"center",justifyContent:"center",borderRadius:radius.pill,backgroundColor:colors.surfaceSecondary,...shadows.card},topTitle:{fontSize:17,fontWeight:"800",color:colors.onSurface},card:{backgroundColor:colors.surfaceSecondary,borderRadius:radius.lg,padding:spacing.lg,marginBottom:spacing.md,...shadows.card},row:{flexDirection:"row",alignItems:"center",gap:spacing.md},title:{fontSize:16,fontWeight:"800",color:colors.onSurface},status:{fontSize:12,color:colors.onSurfaceMuted,marginTop:2,textTransform:"capitalize"},amount:{fontSize:18,fontWeight:"800",color:colors.onSurface},meta:{fontSize:12,color:colors.onSurfaceMuted,marginTop:spacing.sm},input:{backgroundColor:colors.surfaceTertiary,borderRadius:radius.md,paddingHorizontal:spacing.md,minHeight:46,color:colors.onSurface,marginTop:spacing.md},providerWait:{flexDirection:"row",alignItems:"center",gap:spacing.sm,marginTop:spacing.md,padding:spacing.md,backgroundColor:colors.surfaceTertiary,borderRadius:radius.md},providerWaitText:{flex:1,fontSize:12,color:colors.onSurfaceMuted,lineHeight:17}});
